### ISSUE TITLE
Sitio público - Sección Presupuesto - Gráfico

### ISSUE THREAD

**Issue by ing-araceli-c** [INAImexico/Transparencia-en-Publicidad-Oficial-TPO#12]
Es necesario que el gráfico muestre los datos del año seleccionado en el combo "Ejercicio". Actualmente muestra el total ejercido en cada partida en todos los años registrados.

**Comment by M0rpheus** [comment]
![87dlg](https://user-images.githubusercontent.com/858651/27497654-63941720-5821-11e7-8bd3-fedf333d2015.jpg)

**Comment by n4utilius** [comment]
CAMBIO EN /home/pruebas5/public_html/tpo_qroo_05_06_17/tpov1/application/models/Graficas_model.php

**(select sum(z.monto_desglose) from vact_facturas as y, vact_facturas_desglose as z, cat_ejercicios as x where y.id_factura = z.id_factura and 
y.id_presupuesto_concepto =a.id_presupuesto_concepto and x.id_ejercicio = y.id_ejercicio and x.ejercicio = '" . $ejercicio .  "') as monto_ejercido,**
(sum(a.monto_presupuesto) + sum(a.monto_modificacion)) as monto_total

**Comment by n4utilius** [comment]
Si bien, los datos de subtotales ahora funcionan, pueden no coincidir con los totales (este es el caso del año 2017 en la plataforma Queretaro)

La razón es que el origen de los datos totales, viene de una tabla de reporte general, que aparentemente surge de una captura manual, en cambio, los subtotales vienen de la sumatoria de los detalles de factura.
