### ISSUE TITLE
Sitio público - Sección Presupuesto - Columna "presupuesto ejercido"

### ISSUE THREAD

**Issue by ing-araceli-c** [INAImexico/Transparencia-en-Publicidad-Oficial-TPO#13]
En la tabla de datos de la sección, es necesario agrupar en la columna "presupuesto ejercido" los montos por año y por partida. Actualmente muestra el total ejercido de cada partida en todos los años registrados.

**Comment by n4utilius** [comment]
Se resolvió agregando una nueva vista:

CREATE VIEW vtab_presupuesto_des AS 
SELECT ej.ejercicio AS ejercicio, con.partida AS partida, con.denominacion AS descripcion,
			 des.monto_presupuesto as original, des.monto_modificacion as modificaciones,
		   ( SUM(des.monto_presupuesto) + SUM(des.monto_modificacion)) AS presupuesto,
		   ( SELECT SUM(fglo.monto_desglose) 
		     FROM tab_facturas fac
		     JOIN tab_facturas_desglose fglo ON fac.id_factura = fglo.id_factura
		     WHERE fac.active = 1 and fglo.active = 1 AND
		     			 fac.id_ejercicio = ej.id_ejercicio AND
		     			 fac.id_presupuesto_concepto = des.id_presupuesto_concepto ) AS ejercido
FROM tab_presupuestos_desglose des
JOIN tab_presupuestos pres ON pres.id_presupuesto = des.id_presupuesto
JOIN cat_ejercicios ej ON ej.id_ejercicio = pres.id_ejercicio
JOIN cat_presupuesto_conceptos con ON con.id_presupesto_concepto = des.id_presupuesto_concepto
GROUP BY con.denominacion, ej.ejercicio;

se hicieron las comprobaciones pertinentes usando como base la tabla 'tab_facturas_desglose' para verificar los totales
