### ISSUE TITLE
Sitio Público - Inicializar la herramienta con el año en curso en "Ejercicio"

### ISSUE THREAD

**Issue by ing-araceli-c** [INAImexico/Transparencia-en-Publicidad-Oficial-TPO#14]
Inicializar la herramienta en ejercicio con en año en curso en lugar de "Todos los años"

![sitio_publico_11jul17-min-1](https://user-images.githubusercontent.com/10039344/28086063-50b81734-6643-11e7-8bac-c41f5c3676a3.png)

**Comment by JArielMG** [comment]
En la sección "Inicio" no se inicialíza la herramienta con el año en curso en "Ejercicio".

Es necesario que el filtro "Ejercicio" de todas las secciones en el front, se actualice automáticamente con el  mayor valor registrado en el back en la ruta: Catálogos/Otros/Ejercicios (Con estatus activo)
