### ISSUE TITLE
Grafico Gasto por Tipo de servicio

### ISSUE THREAD

**Issue by n4utilius** [INAImexico/Transparencia-en-Publicidad-Oficial-TPO#15]
http://publicidadoficial.inai.org.mx/tpov1/Sys_Hub?v=Porservicio&g=pages

El gráfico de pay se encima sobre el de barras.

**Comment by JArielMG** [comment]
![grafico gasto por tipo de servicio](https://user-images.githubusercontent.com/21345593/29529250-8fb88b76-8664-11e7-97d9-6d4f62e7c063.png)

**Comment by JArielMG** [comment]
![grafico gasto por tipo de servicio-2017](https://user-images.githubusercontent.com/21345593/29529257-96f0e79e-8664-11e7-82e6-50ad6bb6338f.png)

**Comment by n4utilius** [comment]
corregido
![nuevo_formato_graficas](https://user-images.githubusercontent.com/920186/31088596-cf430258-a766-11e7-9887-44b9b089a236.png)
