### ISSUE TITLE
Sitio Público - Todas las secciones

### ISSUE THREAD

**Issue by JArielMG** [INAImexico/Transparencia-en-Publicidad-Oficial-TPO#16]
En relación a la modificación del commit: "colocar correctamente las urls de los recursos"

https://github.com/INAImexico/Transparencia-en-Publicidad-Oficial-TPO/commit/bf809913e6fe3419155f4cda452ee617e348c1fb

Se realiza la instalación de la herramienta en la url siguiente:

http://pruebasti.com.mx/inai_fundar_v28sep17/tpov1/

Se detecta que la visualización del sitio público en todas las secciones, no es la correcta.

**Comment by JArielMG** [comment]
Ejemplos:


![inicio](https://user-images.githubusercontent.com/21345593/30979865-a59a1dbc-a444-11e7-897d-e1b5b979f5cb.png)
![campanas](https://user-images.githubusercontent.com/21345593/30979915-c5f879a0-a444-11e7-9aaa-5f4d0b93a2af.png)

**Comment by JArielMG** [comment]
En una instalación con los datos del instituto se visualiza de igual forma. 

La url de la instalación es:

http://pruebasti.com.mx/inai_fundar_v28sep/tpov1/

**Comment by JArielMG** [comment]
Ejemplo:
![campanas](https://user-images.githubusercontent.com/21345593/30980859-125a091e-a448-11e7-9ed0-4caec428239a.png)
![sujetos](https://user-images.githubusercontent.com/21345593/30980868-1a0aec96-a448-11e7-97c2-06ff7c43e5cc.png)

**Comment by n4utilius** [comment]
Listo!!!

el error concistia en que ahora todas (o su mayoría) de las rutas de los recursos dependen de la variable 'base_url' la cual debe configurarse cada vez que se instala en un servidor.

Esto se hizo de así para que en los recursos no se pusiera una y otra vez la ruta del servidor, si no solamente "echo base_url(); "

![cambio](https://user-images.githubusercontent.com/920186/31087866-4c989e64-a764-11e7-8dee-0bf1a17ad352.png)
