### ISSUE TITLE
Descarga de datos en el formato del SIPOT (Art. 70, Frac. XXIII)

### ISSUE THREAD

**Issue by JArielMG** [INAImexico/Transparencia-en-Publicidad-Oficial-TPO#2]
Corregir descarga de datos conforme a la última versión del formato de la frac XXIII del artículo 70 del SIPOT

**Comment by ing-araceli-c** [comment]
[LGTA70FXXIII.zip](https://github.com/INAImexico/Transparencia-en-Publicidad-Oficial-TPO/files/1103121/LGTA70FXXIII.zip)

**Comment by ing-araceli-c** [comment]
En la instalación del Gobierno del Estado de Chihuahua, arroja el siguiente error.

"Error Number: 1242. Subquery returns more than 1 row"

![Uploading Chihuahua_26jun17.png…]()

**Comment by n4utilius** [comment]
se necesitan más detalles para resolver este issue, sería conveniente contar con una copia de la data o acceso al sistema de Chihuahua

**Comment by JArielMG** [comment]
Se realizó la validación de la descarga del archivo PNT.zip dicha descarga se realiza de forma correcta.

Sin embargo al validar los archivos contenidos dentro del archivo zip detectamos lo siguiente. 

Observaciones:
1. El archivo llamado “F70FXXIIIB_tabla_10633” descarga los datos de las columnas “Presupuesto ejercido al periodo” y “Presupuesto total ejercido por concepto” de forma global (suma total), lo correcto es que descargue los montos por partida y ejercicio. Corrección que se realizó en el front en la sección “Presupuesto” en la columna “Presupuesto ejercido” de la tabla respectiva.

2. En todos los archivos se detecta que el formato de codificación en el que se descargan los datos no es el adecuado, ya que en los títulos de las columnas las letras con acento se muestran con símbolos.

3. El orden de las columnas de los archivos que se descargan en el achivo PNT.zip no es el correcto de acuerdo a la última versión del formato de la frac XXIII del artículo 70 del SIPOT. En el archivo siguiente se encuentra la comparación y el orden de las columnas de cada archivo que se requiere:
https://docs.google.com/spreadsheets/d/1suPisDdXQyKfSMxxN50MyOueWgTi75swAvIPyPUB5A8/edit?usp=sharing

**Comment by JArielMG** [comment]
[Orden de columnas.zip](https://github.com/INAImexico/Transparencia-en-Publicidad-Oficial-TPO/files/1198205/Orden.de.columnas.zip)

**Comment by JArielMG** [comment]
Revisión 07ago17. Derivada del cambio en archivos descargables el día 04 de agosto.

Observaciones:
1. En el archivo llamado “F70FXXIIIB_tabla_10633” los datos de la columna “Presupuesto ejercido al periodo” ya muestra los valores correctos. Sin embargo la columna “Presupuesto total ejercido por concepto” sigue mostrando los valores de forma global (suma total), no desglosa los montos por partida y ejercicio correspondientes.

2.  En el formato de codificación en los archivos descargados, los títulos de las columnas las letras con acento se muestran con símbolos.

3. El orden de las columnas en cada archivo ya es el correcto. 

Sin embargo:
a) En el archivo llamado "F70FXXIIIB_tabla_10632" la información registrada se mantuvo en el orden anterior de descarga, provocando que la información en cada columna no corresponda al título de la misma.

b) En el archivo llamado "F70FXXIIIB_tabla_10656" la información registrada se descarga en el orden establecido de las columnas hasta la fila 28, a partir de la línea 29 el orden de la información cambia y se desordena

**Comment by JArielMG** [comment]
[TPO - Issue #2 Descarga_PNT.pdf](https://github.com/INAImexico/Transparencia-en-Publicidad-Oficial-TPO/files/1205986/TPO.-.Issue.2.Descarga_PNT.pdf)

**Comment by n4utilius** [comment]
Actualización de Vistas
DROP VIEW vprovee_1;
CREATE VIEW vprovee_1 AS
select distinct proveedor as lista, ejercicio from vpor_proveedor where total >= 0
union select distinct categoria as lista, ejercicio from vpor_proveedor where total >= 0
union select distinct tipo as lista, ejercicio from vpor_proveedor where total >= 0; 

DROP VIEW vgrafica1;
CREATE VIEW vgrafica1 AS
SELECT a.ejercicio AS ejercicio, a.servicio AS servicio, a.campana AS campana,
a.partida AS partida, a.ejercido AS ejercido, a.tipo AS tipo, a.fecha AS fecha,
a.proveedor AS proveedor, a.campana_aviso AS campana_aviso,
( SELECT SUM(monto_presupuesto) / (SELECT COUNT(0) FROM vpregrafica1 b) FROM tab_presupuestos_desglose ) AS presupuesto,
( SELECT SUM(des.monto_desglose)
FROM tab_facturas fac
JOIN tab_facturas_desglose des ON fac.id_factura = des.id_factura
WHERE fac.active = 1 AND des.active = 1
) / (SELECT COUNT(0) FROM vpregrafica1 b) AS modificacion,
( SELECT COUNT(0) FROM vprovee_1 
WHERE vprovee_1.ejercicio = a.ejercicio
AND vprovee_1.lista NOT IN ('Análisis, estudios y métricas', 'Gastos de propaganda e Imagen', 'Impresiones', 'Internet', 'Medios impresos', 'Producción de contenidos', 'Radio', 'Televisión', 'Contratos', 'Órdenes de compra')
) / (SELECT COUNT(0) FROM vpregrafica1 b 
where b.ejercicio = a.ejercicio and proveedor NOT IN ('Análisis, estudios y métricas', 'Gastos de propaganda e Imagen', 'Impresiones', 'Internet', 'Medios impresos', 'Producción de contenidos', 'Radio', 'Televisión', 'Contratos', 'Órdenes de compra')) AS proveedores,
( SELECT COUNT(0) FROM tab_campana_aviso z WHERE z.periodo = a.ejercicio AND active = 1) / (SELECT COUNT(0) FROM vpregrafica1 b where b.ejercicio = a.ejercicio) AS totalcampanas
FROM vpregrafica1 a;

**Comment by JArielMG** [comment]
Revisión 08ago17

Observaciones:

1. En el archivo llamado “F70FXXIIIB_tabla_10633” los datos de la columna “Presupuesto total ejercido por concepto” sigue mostrando los valores de forma global (suma total), no desglosa el monto por partida y ejercicio correspondiente.

2. En el archivo llamado "F70FXXIIIB_tabla_10632" las columnas:
     -Procedimiento de contratación
     -Fundamento jurídico
     -Razones que justifican la elección
Descarga los datos de manera incorrecta y desordenada.

3. En el archivo llamado "F70FXXIIIB_tabla_10656" la información registrada se descarga en el
orden establecido de las columnas hasta la fila 28, a partir de la línea 29 el orden de la
información cambia y se desordena.

**Comment by JArielMG** [comment]
[TPO - Issue #2 08ago17 Descarga_PNT.pdf](https://github.com/INAImexico/Transparencia-en-Publicidad-Oficial-TPO/files/1209878/TPO.-.Issue.2.08ago17.Descarga_PNT.pdf)

**Comment by JArielMG** [comment]
Después de los últimos cambios, la descarga de archivos queda con el siguiente estatus:

1. Tabla_10632, descarga los datos en el orden correcto, pero de manera incompleta. Descarga los datos hasta el registro 27, siendo que tenemos registrados 330.

2. Tabla_10633, en la primer columna "ID Respecto a los recursos y el presupuesto (Factura-Orden de compra-Contrato-Proveedor), no descarga la información registrada en el "Ejercicio 2016"

3. Ha sido corregido este punto, respecto a la descarga del archivo Tabla_10656

**Comment by JArielMG** [comment]
![tabla_10632](https://user-images.githubusercontent.com/21345593/29529280-a9f11594-8664-11e7-9e65-f4404e0690f3.png)

**Comment by JArielMG** [comment]
![tabla_10633](https://user-images.githubusercontent.com/21345593/29540844-32d080f8-8696-11e7-8513-983e09f2a665.png)

**Comment by JArielMG** [comment]
Descarga de archivo "F70FXXIIIB_tabla_10633" de la PNT. Corregir la suma de los montos totales de la columna: Presupuesto total ejercido por concepto, los montos mostrados deben de ser la suma total de los montos ejercidos que correspondan a la misma partida sin tomar en cuenta el ejercicio en el cual se ejerció el gasto, estos montos son tomados de la columna "Presupuesto ejercido al periodo"

**Comment by JArielMG** [comment]
Descarga actual
![descarga actual](https://user-images.githubusercontent.com/21345593/31240280-bb7cd846-a9c5-11e7-9e19-5d1d8bbd0022.png)
