### ISSUE TITLE
Sitio público - Sección Presupuesto

### ISSUE THREAD

**Issue by ing-araceli-c** [INAImexico/Transparencia-en-Publicidad-Oficial-TPO#3]
Al aplicar los filtros del combo "ejercicio", el monto "Presupuesto ejercido" de las cifras destacadas no corresponde a los datos contenidos en la tabla de la misma sección (columna "Presupuesto ejercido") .

**Comment by n4utilius** [comment]
Reparado con la resolución del bug #12 y #8
(sujeto a revisión)
