### ISSUE TITLE
Sitio público - Modificación de configuración para actualización de gráficos en tiempo real

### ISSUE THREAD

**Issue by ing-araceli-c** [INAImexico/Transparencia-en-Publicidad-Oficial-TPO#4]
Probablemente no se trate de un problema de cookies sino de los archivos intermedios de datos a partir de los cuales se generan las vistas del sistema. De esta manera se sugiere hacer alguna modificación a nivel del servidor, del software sobre dichos archivos intermedios para que se actualice en tiempo real la información.

**Comment by JArielMG** [comment]
Error en la sección presupuesto 

URL de instalación
http://pruebasti.com.mx/tpov1_031017/tpov1/Sys_Hub?v=Presupuesto&g=pages

Error en la sección inicio en el área de las gráficas
URL instalación
http://pruebasti.com.mx/tpov1_031017/tpov1/

**Comment by JArielMG** [comment]
Se soluciona la gráfica de la sección presupuesto.

Se soluciona el área de los gráficos de la sección inicio.

URL instalación de validación
http://pruebasti.com.mx/inai_fundar_v10oct17/tpov1/
