### ISSUE TITLE
Sitio público - Cifras destacadas

### ISSUE THREAD

**Issue by JArielMG** [INAImexico/Transparencia-en-Publicidad-Oficial-TPO#8]
Revisar y validar las cifras destacadas y operaciones, principalmente de la secciones inicio, presupuesto y proveedores.

**Comment by n4utilius** [comment]
Cambio de variable total_ejercido en gráfica de presupuesto 
de
(select sum(ejercido) from vtab_presupuesto where ejercicio = '". $ejercicio . "' ) as monto_ejercido,
a
(select sum(z.monto_desglose) from vact_facturas as y, vact_facturas_desglose as z, cat_ejercicios as x 
where y.id_factura = z.id_factura and x.id_ejercicio = y.id_ejercicio and x.ejercicio = '" . $ejercicio .  "') as monto_ejercido,

**Comment by LilianAnaya** [comment]
[08issue-TPODatosQroo.pdf](https://github.com/INAImexico/Transparencia-en-Publicidad-Oficial-TPO/files/1125601/08issue-TPODatosQroo.pdf)

**Comment by n4utilius** [comment]
**Cambio en la vista  vgrafica1**
DROP VIEW vgrafica1;
CREATE VIEW vgrafica1 AS
SELECT a.ejercicio AS ejercicio, a.servicio AS servicio, a.campana AS campana, 
a.partida AS partida, a.ejercido AS ejercido, a.tipo AS tipo, a.fecha AS fecha, 
a.proveedor AS proveedor, a.campana_aviso AS campana_aviso,
( SELECT SUM(monto_presupuesto) / (SELECT COUNT(0) FROM vpregrafica1 b) FROM tab_presupuestos_desglose ) AS presupuesto, 
( SELECT SUM(des.monto_desglose)
FROM tab_facturas fac
JOIN tab_facturas_desglose des ON fac.id_factura = des.id_factura
WHERE fac.active = 1 AND des.active = 1
) / (SELECT COUNT(0) FROM vpregrafica1 b) AS modificacion,
( SELECT COUNT(0) FROM tab_proveedores z WHERE z.periodo = a.ejercicio AND active = 1) /  (SELECT COUNT(0) FROM vpregrafica1 b where b.ejercicio =  a.ejercicio )  AS proveedores, 
( SELECT COUNT(0) FROM tab_campana_aviso z WHERE z.periodo = a.ejercicio AND active = 1) / (SELECT COUNT(0) FROM vpregrafica1 b where b.ejercicio =  a.ejercicio) AS totalcampanas
FROM vpregrafica1 a;

**Comment by JArielMG** [comment]
Se validan los valores mostrados en las cifras destacadas de la sección inicio, comparando los datos mostrados con cada una de las secciones respectivas.

En el combo Ejercicio seleccionando el filtro **“Todos”**, detectamos que la cifra de 
“Proveedores” 
no es igual a la cifra mostrada en la sección Proveedores. Lo correcto es la cifra mostrada en la sección Proveedores.

En el combo Ejercicio seleccionando el filtro **“2015”**, detectamos que la cifras de 
“Presupuesto ($)” 
“Modificación ($)” 
“Proveedores” 
“Campañas/Avisos” 
no son iguales a las cifras mostradas en cada sección respectiva, las cuales son correctas.

En el combo Ejercicio seleccionando el filtro **“2016”**, detectamos que la cifras de 
“Presupuesto ($)” 
“Modificación ($)”
“Ejercido ($)” 
“Proveedores” 
“Campañas/Avisos” 
no son iguales a las cifras mostradas en cada sección respectiva, las cuales son correctas.

En el combo Ejercicio seleccionando el filtro **“2017”**, detectamos que la cifras de “Presupuesto ($)” 
“Modificación ($)”
“Ejercido ($)” 
“Proveedores” 
no son iguales a las cifras mostradas en cada sección respectiva, las cuales son correctas.

**Comment by JArielMG** [comment]
[TPO - Issue #8 Datos_INAI.pdf](https://github.com/INAImexico/Transparencia-en-Publicidad-Oficial-TPO/files/1198033/TPO.-.Issue.8.Datos_INAI.pdf)

**Comment by n4utilius** [comment]
Cambio a 
DROP VIEW vgrafica1;
CREATE VIEW vgrafica1 AS
SELECT a.ejercicio AS ejercicio, a.servicio AS servicio, a.campana AS campana,
a.partida AS partida, 
(SELECT sum( b.monto_desglose ) as valor2 FROM vact_facturas as f, vact_facturas_desglose as b, vact_ejercicios as c WHERE f.id_factura = b.id_factura AND f.id_ejercicio = c.id_ejercicio and c.ejercicio = a.ejercicio) / 
(SELECT COUNT(0) FROM vpregrafica1 b WHERE ejercicio = a.ejercicio) AS ejercido,
a.tipo AS tipo, a.fecha AS fecha,
a.proveedor AS proveedor, a.campana_aviso AS campana_aviso,
( (select sum(original) as "valor1" from vtab_presupuesto where ejercicio = a.ejercicio) / (SELECT COUNT(0) FROM vpregrafica1 b WHERE ejercicio = a.ejercicio)  ) AS presupuesto,
( select sum(presupuesto) as "valor3" from vtab_presupuesto where ejercicio = a.ejercicio) / (SELECT COUNT(0) FROM vpregrafica1 b WHERE ejercicio = a.ejercicio) AS modificacion,
( select count(0) as valor1  from vtab_proveedores WHERE ejercicio = a.ejercicio AND nombre NOT IN ("Análisis, estudios y métricas", "Gastos de propaganda e Imagen", "Impresiones", "Internet", "Medios impresos", "Producción de contenidos", "Radio", "Televisión", "Contratos", "Órdenes de compra")
) / (SELECT COUNT(0) FROM vpregrafica1 b 
where b.ejercicio = a.ejercicio and proveedor NOT IN ('Análisis, estudios y métricas', 'Gastos de propaganda e Imagen', 'Impresiones', 'Internet', 'Medios impresos', 'Producción de contenidos', 'Radio', 'Televisión', 'Contratos', 'Órdenes de compra')) AS proveedores,
( SELECT COUNT( * ) as valor1 FROM vact_campana_aviso c, vact_ejercicios as b, cat_ejercicios e WHERE c.id_campana_tipo IN (1,2) AND c.id_ejercicio = b.id_ejercicio AND b.id_ejercicio = e.id_ejercicio AND e.ejercicio = a.ejercicio) / (SELECT COUNT(0) FROM vpregrafica1 b where b.ejercicio = a.ejercicio) AS totalcampanas
FROM vpregrafica1 a;

**Comment by JArielMG** [comment]
Las cifra destacada en la sección Inicio, correspondiente al número de proveedores en el filtro de ejercicio "Todos", no muestra la cifra correcta. Esta cifra ya se mostraba correctamente pero ahora vuelve a ser incorrecta.

Incorrecto

URL de instalación
http://pruebasti.com.mx/tpov1_031017/tpov1/
![inicio-ejercicio incorrecto](https://user-images.githubusercontent.com/21345593/31139835-6751911e-a838-11e7-84e6-368dd0beba87.png)

Correcto

URL de instalación
http://pruebasti.com.mx/inai_fundar_v23ago17/tpov1/

**Comment by JArielMG** [comment]
URL de validación del correcto funcionamiento de las cifras destacadas de inicio.

http://pruebasti.com.mx/inai_fundar_v03oct17/tpov1/
